name: vqc-a1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - pip:
    - pennylane==0.32
    - torch==2.0.1
    - optuna==3.4
    - statsmodels==0.14
    - rdkit==2023.9
    - scikit-learn==1.3
    - pandas==2.0
    - numpy==1.24
    - matplotlib==3.7
    - seaborn==0.12
    - click==8.1
    - requests==2.31
    - pytest==7.4
